name: Building Image and Pushing to GHCR
on: [push]
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building image for ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extra_args: "--build-arg VITE_HOST="